name: Mustache Templating Maven Plugin Build

on: [ push ]

jobs:
    build:
        name: Maven Build
        runs-on: ubuntu-latest

        steps:
        -   uses: actions/checkout@v4

        -   name: Set up JDK 8
            uses: actions/setup-java@v4
            with:
                java-version: 8
                distribution: temurin
                architecture: x64
                cache: maven

        -   name: Build with Maven
            run: mvn -B verify --file pom.xml

        -   name: Upload Java code coverage reports to Codecov
            uses: codecov/codecov-action@v4
            env:
                CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

#        file: jacoco.xml #optional
#        name: codecov-umbrella #optional
#        yml: ./codecov.yml #optional
#        fail_ci_if_error: true #optional (default = false)
